  - alias: 'Lights on at sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: switch.turn_on
        entity_id: switch.kitchen
      - service: light.turn_on
        data:
          entity_id: light.side_lights
          brightness_pct: 50
  - alias: 'Lights on at night Summer'
    trigger:
      - platform: time
        at: '18:15:00'
    action:
      - service: switch.turn_on
        entity_id: switch.kitchen
      - service: light.turn_on
        data:
          entity_id: light.side_lights
          brightness_pct: 50
  - alias: 'Lights off on vacation'
    trigger:
      - platform: time
        at: '22:15:00'
    action:
      - service: switch.turn_off
        entity_id: switch.kitchen
      - service: light.turn_off
        data:
          entity_id: light.side_lights
      - service: light.turn_off
        data:
          entity_id: light.great_room
  - alias: 'Lock Garage Door at Night'
    trigger:
      - platform: time
        at: '22:00:00'
    action:
      - service: lock.lock
        data:
          entity_id: lock.schlage_be469_touchscreen_deadbolt_locked 
  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homekit.start