  - alias: 'Lights on at sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: switch.turn_on
        entity_id: switch.kitchen
      - service: light.turn_on
        data:
          entity_id: light.side_lights
          brightness_pct: 50
  # - alias: 'Christmas Tree On'
  #   trigger:
  #     - platform: sun
  #       event: sunset
  #   action:
  #     service: switch.turn_on
  #     entity_id: switch.christmas_tree
  # - alias: 'Christmas Tree Off'
  #   trigger:
  #     platform: time
  #     at: '23:00:00'
  #   action:
  #     service: switch.turn_off
  #     entity_id: switch.christmas_tree