  - alias: 'Lights on at sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: switch.turn_on
        entity_id: switch.kitchen
      - service: light.turn_on
        data:
          entity_id: light.side_lights
          brightness_pct: 50