homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    zwave:
      hidden: true
    zha:
      hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - panasonic_viera
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# HUSBZB-1 USB stick
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret z_wave_network_key

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

ffmpeg:

ios:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  structure:
    - Home

ring:
  username: !secret ring_username
  password: !secret ring_password

sensor:
  - platform: ring

camera:
  - platform: foscam
    name: !secret foscam_1_name
    ip: !secret foscam_1_ip
    username: !secret foscam_1_username
    password: !secret foscam_1_password
  - platform: ffmpeg
    input: !secret foscam_2_rtsp_input
    name: !secret foscam_2_name

cover:
  - platform: myq
    username: !secret myq_username 
    password: !secret myq_password
    type: chamberlain

climate:
  - platform: nest

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

emulated_hue:
  host_ip: 10.0.0.7
  listen_port: 8300
  expose_by_default: false
  exposed_domains:
    - switch
  entities:
    switch.christmas_tree:
      name: "Christmas Tree"
      hidden: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
